adding a task on obtaining a DOI for your code release
EVERSE-ResearchSoftware/RSQKit pull request #73
Opened 2024-10-14 17:43 UTC by shoaibsufi

There seems to be a clash or strong overlap in the spreadsheet - row 9 (this one) and row 27 on the 'RSQkit pages' spreadsheet (that spreadsheet is publicly accessible so not adding the link here).

The row 27 related branch and page is here - https://github.com/EVERSE-ResearchSoftware/RSQKit/blob/git_zenodo/pages/your_tasks/publish_to_zenodo.md 

I guess this points at sanity checking outstanding entries in the future to avoid duplication.

The other page is more involved - and could perhaps be recast as a more advanced one.

2024-10-14 17:49 UTC, shoaibsufi commented
I could not find José Mª Fernández's GitHub user - he was down to review on the spreadsheet - and the issue of the clash came up so I thought it would be best to have yourselves (@anenadic and @dgarijo) down as reviewers.

2024-10-18 16:54 UTC, dgarijo commented on pages/your_tasks/zenodo_doi.md
> +	* Click on releases and then on Draft a new release
Maybe here link to "how to create a code release" task?

2024-10-18 16:54 UTC, dgarijo commented on pages/your_tasks/zenodo_doi.md
> +	* Click on releases and then on Draft a new release
It covers how to do it and the versioning used

2024-10-18 16:57 UTC, dgarijo commented on pages/your_tasks/zenodo_doi.md
> +	* After the GitHub release, go to Zenodo, where you will see your repository archived with a DOI assigned to it
We should state how to get the badge. 
In "details", click on the badge:
![image](https://github.com/user-attachments/assets/616d5f3d-e723-4065-9dc3-a4faeeae8c0c)
Then copy the markdown code in your readme. It should show as follows:
![image](https://github.com/user-attachments/assets/0f8e366f-9a11-40d7-a75b-11ef9fa50336)

2024-10-18 17:05 UTC, dgarijo commented on pages/your_tasks/zenodo_doi.md
> +Obtaining a DOI (a type of persistent identifier) for your software has become [increasingly popular][datacite-doi-software]. So, how do you obtain a DOI (a type of persistent identifier) to refer to
```suggestion
Obtaining a DOI (a type of persistent identifier) for your software has become [increasingly popular][datacite-doi-software] to indicate others how to cite your software (either in a publication or as an independent way of referring to your software versions). In this document we describe how to obtain a DOI to refer to your software releases.
```

2024-10-18 17:05 UTC, dgarijo commented on pages/your_tasks/zenodo_doi.md
> +contributors: ["Shoaib Sufi"]
```suggestion
contributors: ["Shoaib Sufi", "Daniel Garijo"] 
```
if reviewers are contribs, these should be acknowledged too no?

2024-10-18 17:06 UTC, dgarijo requested changes
Hi @shoaibsufi nice work. I added a couple of suggestions.
Do you want to implement them, or shall I merge and commit them myself?

2024-10-20 10:32 UTC, dgarijo commented
@shoaibsufi in the interest of time I will do a PR and push some minor changes. Thanks!

2024-10-20 10:32 UTC, merged